### ISSUE TITLE
Software engineer (Mid - Sr) at Hatchback

### ISSUE THREAD

**Issue by mattapperson** [nodeschool/jobs#1]
# Software Engineer (Mid - Sr)
#### Anywhere in the US (remote)

We are looking for a solid engineer who thinks working on massive data sets using [Aerospike](http://www.aerospike.com/), ElasticSearch and of course NodeJS.
You will be working in a distributed team, so strong communication skills
and teamwork is a requirement. Remote workers are fully supported.
### Our tech stack includes:

```
* Obj-C (iOS) 
* Java (Android)
* NodeJS (using the Hapi framework)
* ReactJS / Fluxible 
* Aerospike
* ElasticSearch
* CoreOS and Docker
```
### Ideal candidates have:
- Understanding of RESTful APIs.
- Prior experience and a willingness to participate in open source projects.
- Independence and an ability to get things done without direct oversight (our team is fully remote).
- Great communication skills, empathy and patience.
- A commitment to shipping high quality code and delivering a consistent and excellent customer experience.
- Experience with testing tools such as mocha.
- Some Obj-C or Java experience (not required, but a major plus)
- You know GIT beyond a basic GIT push/pull.
- An interest in expanding technical knowledge
### Responsibilities
- Help develop our suite of analytics and <redacted> developer tools
- Provide technical support to developers who are having issues with our services.
- Help to support and expand our REST APIs
- Contribute back to the community via open source projects and PRs
- Collaborate both inside and outside our team at Hatchback to improve our product offering to developers.
- Manage and contribute to our SDKs.

---

**How to Apply**
1. Send an E-mail to [matt@hatchback.me](mailto:matt@hatchback.me) 
2. Tell us a little bit about yourself and your work experience.
3. Include links to completed projects and your Github profile.

---

**More about Hatchback**

We believe in small, focused teams. Small teams are fast and agile. Smaller teams require less overhead and less management. Smaller teams get more tasks completed.

We hire based on character, passion, alignment to our values and compatibility with our culture. While experience is valuable, we are more interested in what you want to do moving forward, your capacity to solve problems, your potential, and your enthusiasm and energy.

**Comment by konobi** [comment]
If it's a remote job, why is it restricted to the US?

**Comment by SomeoneWeird** [comment]
Because sometimes it's easier to manage legalese within the same country. It also has the added benefit of requiring the employee to be in a similar timezone to you.

**Comment by mattapperson** [comment]
That's exactly correct. We had a dev in the UK for a while and it was a paperwork/payroll nightmare so we decided to go USA only for now

**Comment by mattapperson** [comment]
I would add that anywhere in the americas we would consider... That at least removes the timezone issue. But we would have to look into the payroll details of whatever country the developer was from.

**Comment by konobi** [comment]
@mattapperson Many of the companies I've worked with before have had luck with services like Trinet.

**Comment by mattapperson** [comment]
@konobi Thanks for the tip, we will look into it!

**Comment by grabbou** [comment]
@mattapperson what about B2B contracts then? Sounds like invoice-based payments would've solved a lot of your issues! But I agree, timezone is a nightmare, especially when working between US and Europe.
